import type { SFSymbol } from 'expo-symbols';

/** Monochrome SF Symbol used when a habit has no icon set. */
export const DEFAULT_HABIT_ICON: SFSymbol = 'circle.fill';

/** Coerce a stored icon string into a typed SF Symbol name. */
export function habitIcon(icon: string | null | undefined): SFSymbol {
  return (icon ?? DEFAULT_HABIT_ICON) as SFSymbol;
}

/** True when a stored icon is an emoji (rendered as text) vs an SF Symbol. */
export function isEmojiIcon(icon: string | null | undefined): icon is string {
  return !!icon && /\p{Extended_Pictographic}/u.test(icon);
}

/** Starter habit suggestions surfaced on first run / in the create form. */
export const HABIT_NAME_SUGGESTIONS: { name: string; icon: SFSymbol }[] = [
  { name: 'Drink water', icon: 'drop.fill' },
  { name: 'Exercise', icon: 'figure.run' },
  { name: 'Read', icon: 'book.fill' },
  { name: 'Meditate', icon: 'brain.head.profile' },
  { name: 'Sleep early', icon: 'moon.fill' },
  { name: 'Walk', icon: 'figure.walk' },
  { name: 'Journal', icon: 'pencil' },
  { name: 'Vitamins', icon: 'pills.fill' },
  { name: 'Save money', icon: 'dollarsign.circle.fill' },
  { name: 'Eat healthy', icon: 'fork.knife' },
];

/** Icons available in the create form (monochrome SF Symbols). */
export const HABIT_ICON_SUGGESTIONS: { key: SFSymbol; label: string }[] = [
  { key: 'circle', label: 'None' },
  { key: 'drop.fill', label: 'Water' },
  { key: 'figure.run', label: 'Run' },
  { key: 'book.fill', label: 'Read' },
  { key: 'brain.head.profile', label: 'Meditate' },
  { key: 'moon.fill', label: 'Sleep' },
  { key: 'dumbbell.fill', label: 'Gym' },
  { key: 'leaf.fill', label: 'Nature' },
  { key: 'cup.and.saucer.fill', label: 'Coffee' },
  { key: 'heart.fill', label: 'Health' },
  { key: 'star.fill', label: 'Star' },
  { key: 'flame.fill', label: 'Streak' },
  { key: 'bolt.fill', label: 'Energy' },
  { key: 'bicycle', label: 'Cycle' },
  { key: 'figure.walk', label: 'Walk' },
  { key: 'fork.knife', label: 'Eat' },
  { key: 'carrot.fill', label: 'Veggies' },
  { key: 'pencil', label: 'Write' },
  { key: 'paintbrush.fill', label: 'Paint' },
  { key: 'music.note', label: 'Music' },
  { key: 'guitars.fill', label: 'Guitar' },
  { key: 'camera.fill', label: 'Photo' },
  { key: 'gamecontroller.fill', label: 'Play' },
  { key: 'dollarsign.circle.fill', label: 'Money' },
  { key: 'cart.fill', label: 'Shop' },
  { key: 'pills.fill', label: 'Meds' },
  { key: 'bed.double.fill', label: 'Rest' },
  { key: 'alarm.fill', label: 'Alarm' },
  { key: 'sun.max.fill', label: 'Sun' },
  { key: 'hands.sparkles.fill', label: 'Care' },
  { key: 'figure.pool.swim', label: 'Swim' },
  { key: 'airplane', label: 'Travel' },
  { key: 'briefcase.fill', label: 'Work' },
  { key: 'laptopcomputer', label: 'Study' },
  { key: 'phone.fill', label: 'Call' },
  { key: 'house.fill', label: 'Home' },
  { key: 'pawprint.fill', label: 'Pet' },
  { key: 'globe', label: 'World' },
  { key: 'wineglass.fill', label: 'Drink' },
  // Fitness & body
  { key: 'figure.strengthtraining.traditional', label: 'Strength' },
  { key: 'figure.cooldown', label: 'Stretch' },
  { key: 'figure.mind.and.body', label: 'Mindful' },
  { key: 'figure.hiking', label: 'Hike' },
  { key: 'figure.yoga', label: 'Yoga' },
  { key: 'figure.run.treadmill', label: 'Treadmill' },
  { key: 'sportscourt.fill', label: 'Court' },
  { key: 'soccerball', label: 'Soccer' },
  { key: 'basketball.fill', label: 'Basketball' },
  { key: 'tennis.racket', label: 'Tennis' },
  { key: 'trophy.fill', label: 'Trophy' },
  { key: 'medal.fill', label: 'Medal' },
  { key: 'flag.checkered', label: 'Finish' },
  { key: 'shoeprints.fill', label: 'Steps' },
  // Health & care
  { key: 'cross.fill', label: 'Medical' },
  { key: 'cross.case.fill', label: 'First aid' },
  { key: 'stethoscope', label: 'Doctor' },
  { key: 'bandage.fill', label: 'Care' },
  { key: 'lungs.fill', label: 'Breathe' },
  { key: 'eye.fill', label: 'Eyes' },
  { key: 'mustache.fill', label: 'Groom' },
  { key: 'comb.fill', label: 'Hair' },
  { key: 'eyeglasses', label: 'Glasses' },
  // Mind & study
  { key: 'graduationcap.fill', label: 'Study' },
  { key: 'books.vertical.fill', label: 'Books' },
  { key: 'text.book.closed.fill', label: 'Textbook' },
  { key: 'newspaper.fill', label: 'News' },
  { key: 'list.bullet.clipboard.fill', label: 'Tasks' },
  { key: 'checklist', label: 'Checklist' },
  { key: 'lightbulb.fill', label: 'Idea' },
  { key: 'puzzlepiece.fill', label: 'Puzzle' },
  // Creativity
  { key: 'paintpalette.fill', label: 'Art' },
  { key: 'theatermasks.fill', label: 'Theater' },
  { key: 'pianokeys', label: 'Piano' },
  { key: 'music.mic', label: 'Sing' },
  { key: 'video.fill', label: 'Video' },
  { key: 'photo.fill', label: 'Photo' },
  { key: 'film.fill', label: 'Film' },
  { key: 'dice.fill', label: 'Dice' },
  // Food & drink
  { key: 'takeoutbag.and.cup.and.straw.fill', label: 'Takeout' },
  { key: 'mug.fill', label: 'Tea' },
  { key: 'birthday.cake.fill', label: 'Cake' },
  // Home & chores
  { key: 'house.fill', label: 'Home' },
  { key: 'building.2.fill', label: 'Building' },
  { key: 'sofa.fill', label: 'Couch' },
  { key: 'shower.fill', label: 'Shower' },
  { key: 'bathtub.fill', label: 'Bath' },
  { key: 'washer.fill', label: 'Laundry' },
  { key: 'sink.fill', label: 'Dishes' },
  { key: 'trash.fill', label: 'Trash' },
  { key: 'hammer.fill', label: 'Build' },
  { key: 'wrench.and.screwdriver.fill', label: 'Fix' },
  // Money
  { key: 'creditcard.fill', label: 'Card' },
  { key: 'banknote.fill', label: 'Cash' },
  { key: 'eurosign.circle.fill', label: 'Euro' },
  { key: 'chart.line.uptrend.xyaxis', label: 'Growth' },
  { key: 'chart.bar.fill', label: 'Stats' },
  // Time & planning
  { key: 'calendar', label: 'Calendar' },
  { key: 'clock.fill', label: 'Time' },
  { key: 'timer', label: 'Timer' },
  { key: 'hourglass', label: 'Hourglass' },
  { key: 'bell.fill', label: 'Reminder' },
  { key: 'checkmark.seal.fill', label: 'Done' },
  { key: 'target', label: 'Goal' },
  { key: 'flag.fill', label: 'Flag' },
  // Comms & tech
  { key: 'envelope.fill', label: 'Email' },
  { key: 'message.fill', label: 'Message' },
  { key: 'wifi', label: 'Wifi' },
  { key: 'gearshape.fill', label: 'Settings' },
  { key: 'battery.100', label: 'Battery' },
  // Outdoors & travel
  { key: 'car.fill', label: 'Car' },
  { key: 'bus.fill', label: 'Bus' },
  { key: 'tram.fill', label: 'Train' },
  { key: 'fuelpump.fill', label: 'Fuel' },
  { key: 'map.fill', label: 'Map' },
  { key: 'mappin.and.ellipse', label: 'Place' },
  { key: 'mountain.2.fill', label: 'Mountain' },
  { key: 'tent.fill', label: 'Camp' },
  { key: 'beach.umbrella.fill', label: 'Beach' },
  // Weather & nature
  { key: 'cloud.fill', label: 'Cloud' },
  { key: 'cloud.rain.fill', label: 'Rain' },
  { key: 'snowflake', label: 'Snow' },
  { key: 'wind', label: 'Wind' },
  { key: 'tree.fill', label: 'Tree' },
  { key: 'sparkles', label: 'Sparkle' },
  // Animals
  { key: 'tortoise.fill', label: 'Slow' },
  { key: 'hare.fill', label: 'Fast' },
  { key: 'ant.fill', label: 'Ant' },
  { key: 'ladybug.fill', label: 'Bug' },
  { key: 'fish.fill', label: 'Fish' },
  { key: 'bird.fill', label: 'Bird' },
  { key: 'cat.fill', label: 'Cat' },
  { key: 'dog.fill', label: 'Dog' },
  // Fun
  { key: 'gift.fill', label: 'Gift' },
  { key: 'balloon.fill', label: 'Balloon' },
  { key: 'crown.fill', label: 'Crown' },
  { key: 'sparkle', label: 'Shine' },
];
